---
title: Your Name
description: Your personal website
baseurl: "/" # 基本的なURLパス
url: https://pontacard.github.io # サイトのURL
# timezone: America/Los_Angeles # タイムゾーン
# minify:
#   css: true
#   html: true

collections:
  publications:
  research:
  activity:

defaults:
  - scope:
      path: ""
    values:
      layout: post
      author: Your Name
      categories: misc

# メニューの設定
menu:
  home: /
  publications: /publications/
  research: /research/
  activity: /activity/
  contact: /contact/

# ページごとの設定
pages:
  - title: Home
    permalink: /
  - title: Contact
    permalink: /contact/

# 投稿の設定
# post_defaults:
#   layout: post
#   published: false

# プラグインの設定
plugins:
  - jekyll-feed
---